export const DEFAULT_KEYWORD = [
  "jobs in singapore",
  "part time jobs singapore",
  "singapore jobstreet",
  "part time jobs",
  "jobstreet sg",
  "singapore indeed",
  "job bank singapore",
  "career sg",
  "indeed sg",
  "career gov sg",
  "fastjobs sg",
  "work from home singapore",
  "career future sg",
  "singapore glassdoor",
  "part time jobs for students",
  "google careers singapore",
  "part time weekend jobs",
  "singapore jobsdb",
  "temporary jobs",
  "part time",
  "accenture singapore",
  "jobsdb sg",
  "singapore job vacancy",
  "jobs bank singapore",
  "job search singapore",
  "jobbank sg",
  "google jobs singapore",
  "facebook careers singapore",
  "indeed jobs singapore",
  "fastjobs singapore",
  "jp morgan singapore",
  "gumtree part time jobs",
  "recruitment agency singapore",
  "freelance jobs singapore",
  "admin jobs in singapore",
  "driver jobs in singapore",
  "singapore career",
  "work from home jobs singapore",
  "weekend part time jobs singapore",
  "part time jobs for students in singapore",
  "part time maids",
  "singapore volunteer work",
  "part time retail jobs",
  "singapore job portal",
  "apple singapore career",
  "amazon singapore careers",
  "part time jobs sg",
];

export const DEFAULT_IMAGE = `https://workclass.co/images/seo/open-graph/og-index.png`;
export const DEFAULT_TITLE = `#1 Blue Collar Job Board in Singapore`;
export const DEFAULT_DESCRIPTION = `Need to find a job? WorkClass has you covered with over 9000 job listings and over 1220 employers registered. Find a job today on WorkClass.co`;
